#!/usr/bin/env python3
print("preprestarted")


import RPi.GPIO as GPIO  
import math, sys, os
import subprocess
import socket


print("prestarted")

GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)  


GPIO.setup(18, GPIO.IN, pull_up_down=GPIO.PUD_UP)
GPIO.setup(23, GPIO.IN, pull_up_down=GPIO.PUD_UP)
GPIO.setup(24, GPIO.IN, pull_up_down=GPIO.PUD_UP)
print("started")
c=0
last = 1

def count(pin):
	global c 
	print(c+1)
	c = c + 1

def hip(pin):
	print(str(pin) + ":" + str(GPIO.input(24)))


GPIO.add_event_detect(18, GPIO.BOTH)
GPIO.add_event_detect(24, GPIO.BOTH, callback=hip)

while True:
	try:
		if GPIO.event_detected(18):
			
			try:
				player.kill()
			except NameError:
				pass
			
			current = GPIO.input(18)
			if(last != current):
				if(current == 0):
					GPIO.remove_event_detect(23)
					GPIO.add_event_detect(23, GPIO.BOTH, callback=count, bouncetime=5)
				else:
					GPIO.remove_event_detect(23)
					number = math.floor(c/3)
					if(number == 10):
						number = 0
					player = subprocess.Popen(["mpg123", "/opt/phone/media/" + str(number) + ".mp3", "-q"], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)	
					c=0
				last = GPIO.input(18)
	except KeyboardInterrupt:
		break
